# ------------------------------------------
#  Usage:
#    $> docker-compose up -d
#
# ------------------------------------------

version: '2'

services:
  tapis-documentation:
    image: tapis/tapis-documentation:latest
    container_name: tapis-documentation
    command: './docker-startup.sh'

    ports:
      - "7898:7898"
    volumes:
      - './:/workspace'
