# ------------------------------------------
#  Usage:
#    $> docker-compose up -d
#
# ------------------------------------------

version: '2'

services:
  tapis-documentation:
    #image: tapis/tapis-documentation:latest
    build:
        context: ./
    container_name: tapis-documentation
    command: './docker-startup.sh'

    ports:
      - "0.0.0.0:7898:7898"
    volumes:
      - './:/workspace'
