#!/bin/bash

print_usage(){
    echo "usage: script [-u *username] [-p *password] [-t tenant] [-s site]"
}

## defaults
username=testuser2
password=testuser2
tenant=dev
site=tapis.io

## handle flags
while getopts u:p:t:s:h flag
do
    case "${flag}" in
        h) print_usage; exit 1;;
        u) username=${OPTARG};;
        p) password=${OPTARG};;
        t) tenant=${OPTARG};;
        s) site=${OPTARG};;
    esac
done

echo `$(curl -d '{"username": "$username", "password": "password", "grant_type": "password"}' -H "Content-type: application/json"  https://$tenant.site/v3/oauth2/tokens)`